### ISSUE TITLE
中文字符集

### ISSUE THREAD

**Issue by Charles-LF** [ifrvn/koishi-plugin-send-as-image#1]
想问下这个渲染是需要什么中文字体呢，我系统是ubuntu sever的，下载了**文泉驿等宽**的字体，刷新字体缓存重启后渲染图片中文字符还是一些框框，不知道如何解决

**Comment by ifrvn** [comment]
没有指定中文字体，系统默认中文字体是什么就用的是什么。

安装字体后，重建字体缓存

```
mkfontscale
mkfontdir
fc-cache -fv 
```

然后运行这个命令`fc-list :lang=zh`看下你是否成功安装了中文字体，然后重启koishi即可。

**Comment by Charles-LF** [comment]
安装的字体是Ubuntu仓库里的**龙泉驿**字体,重启服务器和koishi依然不起作用,不知道为啥
![1](https://user-images.githubusercontent.com/96990693/219061579-33b78b68-4a3d-4d6e-87b7-ab5db4ba9dac.jpg)
![image](https://user-images.githubusercontent.com/96990693/219062497-8fbc8d01-5b19-43e5-9147-97cdfa8c2b6c.png)

**Comment by ifrvn** [comment]
![image](https://user-images.githubusercontent.com/21982381/219065925-66b06e4e-0703-4890-8f40-fb5c0d4e4f3c.png)
![image](https://user-images.githubusercontent.com/21982381/219065985-d5f75e19-0bb2-495f-a741-1901473da366.png)

怪啊，我在WSL2里是正常的。

```
sudo apt install fonts-wqy-microhei
sudo apt install fonts-wqy-zenhei
```

我手动导入的ttf也正常

应该是浏览器本身没加载到字体，你装的是chromium-browser吗？

**Comment by Charles-LF** [comment]
这y应该是chromium吧
![image](https://user-images.githubusercontent.com/96990693/219077294-33095551-82cc-4da8-8a90-1cfa688727cc.png)

**Comment by ifrvn** [comment]
那我属实也不知是怎么回事了，或许你可以试试用chrome

**Comment by Charles-LF** [comment]
行吧,我去逝逝

**Comment by ifrvn** [comment]
发了个新版，在 style 里直接 import cdn 的字体，不依赖本地字体了。

~~那么，代价是什么呢~~
