### ISSUE TITLE
功能建议：增加按换行数判断转图的配置项

### ISSUE THREAD

**Issue by Haku530** [ifrvn/koishi-plugin-send-as-image#3]
有些消息虽然长度不长，但因换行数过多也可能导致刷屏类风控，能否在换行符达到一定数量后也触发转图？

**Comment by ifrvn** [comment]
不错的建议，下版本安排

**Comment by ifrvn** [comment]
fixed in f6b920d4748b73f92e04ded24f5056c5030cdebe

**Comment by Haku530** [comment]
您好，我看到github上更新了行数配置项，但是npm上好像没有更新，是不是忘记发布啦？

**Comment by Haku530** [comment]
![image](https://github.com/ifrvn/koishi-plugin-send-as-image/assets/124163849/d2faa527-558e-457c-8b74-405f7c0ceb8e)

**Comment by ifrvn** [comment]
草，难道忘记build了？！

重新发版了

**Comment by Haku530** [comment]
发现发送“帮助”不会转图，但是发送“help”就能正常转图，这是为什么呢

**Comment by ifrvn** [comment]
> 发现发送“帮助”不会转图，但是发送“help”就能正常转图，这是为什么呢

发送“帮助”后拿到的 session.content 是 `<execute>help </execute>`，目前没办法拿到 execute 后的文本，所以没法转。

相关帖子： https://forum.koishi.xyz/t/topic/1656/9?u=ifrank

可以单独发个 issue ，等梦梦哪天解决这个问题了我再修
